#!name=BlockAds RU - Reddit
#!desc=Совместимая отдельная версия. При использовании единого BlockAds RU отключите этот модуль.
#!homepage=https://github.com/pivazyaa/blockads-ru/tree/main/Russia
# SPDX-License-Identifier: GPL-3.0-only
[Script]
RU-Reddit = type=http-response, pattern=^https:\/\/(?:gql(?:-fed)?\.reddit\.com\/?(?:\?[^#]*)?$|(?:(?:www|oauth)\.)?reddit\.com\/(?:r\/[^\/?#]+\/)?(?:hot|new|top|best|rising|comments)(?:\/|\.json(?:\?|$))), requires-body=true, max-size=1048576, timeout=5, engine=jsc, script-path=https://raw.githubusercontent.com/pivazyaa/blockads-ru/39edd9f35c61e32e5aad507805bd02530ea2f9e5/Russia/social-json.js
[MITM]
hostname = %APPEND% gql.reddit.com, gql-fed.reddit.com, oauth.reddit.com, reddit.com, www.reddit.com
