#!name=BlockAds RU - TikTok-Web
#!desc=Совместимая отдельная версия. При использовании единого BlockAds RU отключите этот модуль.
#!homepage=https://github.com/pivazyaa/blockads-ru/tree/main/Russia
# SPDX-License-Identifier: GPL-3.0-only
[Script]
RU-TikTok-Web = type=http-response, pattern=^https:\/\/www\.tiktok\.com\/api\/(?:recommend|post|mix)\/item_list\/(?:\?|$), requires-body=true, max-size=1048576, timeout=5, engine=jsc, script-path=https://raw.githubusercontent.com/pivazyaa/blockads-ru/70cda848e0d89e48e0fdd17ebd7fcb707db08f30/Russia/social-json.js
[MITM]
hostname = %APPEND% www.tiktok.com
